#!/usr/bin/env python3
"""Generate and validate the VistaType Quick Access Toolbar files (Linux-only).

The hidden ribbon tab `tab_LP_and_BRL_QAT_Icons` in src/ribbon/customUI14.xml is what the
toolbar's idQ="x1:btn_*" entries actually resolve against. It is therefore the source of
truth for WHICH VistaType buttons can appear on the toolbar, and with which icon.

This script does two jobs:

  GENERATE  installer/qat-icons-only.officeUI  -- a separator plus VistaType's own buttons and
            nothing else. No mso: entries, and in particular no visible="false", so appending
            it to a user's toolbar can never hide a button they put there themselves.

  VALIDATE  installer/qat-template.officeUI    -- the hand-curated full toolbar. Its layout,
            separators, ordering and the visible="false" entries that suppress Word's default
            buttons are all deliberate, so it is NOT generated. It is only checked: every
            x1:btn_* it names must exist on the hidden tab, with a matching imageMso.

Exits non-zero if the two have drifted, so `make build` refuses to ship a toolbar whose
buttons point at ribbon controls that are not there.

Usage:  python3 tools/lib/build_qat.py [--check-only]
"""
import re
import sys

RIBBON = "src/ribbon/customUI14.xml"
FULL = "installer/qat-template.officeUI"
ICONS_ONLY = "installer/qat-icons-only.officeUI"
HIDDEN_TAB = "tab_LP_and_BRL_QAT_Icons"

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/lib/build_qat.py from the {tab} tab of
     {ribbon} -- do not edit by hand; edit the ribbon tab instead.

     VistaType's own toolbar icons and nothing else. This file is APPENDED to whatever the
     user already has, so it deliberately contains no mso: entries and no visible="false":
     it must never move, hide or reorder a button the user put on their own toolbar.

     Merge-Qat.ps1 substitutes __VT_DOTM_PATH__ with the installed LPandBRL.dotm path. -->
<mso:customUI xmlns:x1="__VT_DOTM_PATH__" xmlns:msox="http://schemas.microsoft.com/office/2006/01/customui/special" xmlns:mso="http://schemas.microsoft.com/office/2009/07/customui">
  <mso:ribbon>
    <mso:qat>
      <mso:sharedControls>
"""

FOOTER = """      </mso:sharedControls>
    </mso:qat>
  </mso:ribbon>
</mso:customUI>
"""


def read(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def hidden_tab_buttons(ribbon_xml):
    """The VistaType <button> entries on the hidden tab: id -> (imageMso, label)."""
    m = re.search(rf'<tab id="{HIDDEN_TAB}".*?</tab>', ribbon_xml, re.S)
    if not m:
        sys.exit(f"ERROR: tab {HIDDEN_TAB} not found in {RIBBON}")
    buttons = {}
    for b in re.finditer(r"<button\b[^>]*/>", m.group(0)):
        el = b.group(0)
        bid = re.search(r'id="([^"]+)"', el)
        img = re.search(r'imageMso="([^"]+)"', el)
        lab = re.search(r'label="([^"]*)"', el)
        if bid:
            buttons[bid.group(1)] = (img.group(1) if img else None,
                                     lab.group(1) if lab else "")
    return buttons


def validate_full(buttons):
    """Every x1:btn_* on the curated toolbar must exist on the hidden tab, same icon."""
    try:
        full = read(FULL)
    except FileNotFoundError:
        print(f"  (skipped: {FULL} not present)")
        return []
    problems = []
    referenced = set()
    for c in re.finditer(r'<mso:control\b[^>]*idQ="x1:([^"]+)"[^>]*/>', full):
        el, bid = c.group(0), c.group(1)
        referenced.add(bid)
        if bid not in buttons:
            problems.append(f"{FULL} references x1:{bid}, which is not on the {HIDDEN_TAB} tab")
            continue
        want = buttons[bid][0]
        got = re.search(r'imageMso="([^"]+)"', el)
        got = got.group(1) if got else None
        if want and got and want != got:
            problems.append(f"{bid}: toolbar icon '{got}' but ribbon icon '{want}'")
    for bid in sorted(set(buttons) - referenced):
        print(f"  note: {bid} is on the hidden tab but not on the curated toolbar")
    return problems


def generate_icons_only(buttons, ribbon_xml):
    """Emit the append-safe file, in the order the buttons appear on the hidden tab."""
    m = re.search(rf'<tab id="{HIDDEN_TAB}".*?</tab>', ribbon_xml, re.S)
    order = [re.search(r'id="([^"]+)"', b.group(0)).group(1)
             for b in re.finditer(r"<button\b[^>]*/>", m.group(0))]

    lines = ['        <mso:separator idQ="msox:vtsep1" visible="true"/>']
    for bid in order:
        img = buttons[bid][0]
        img_attr = f' imageMso="{img}"' if img else ""
        lines.append(f'        <mso:control idQ="x1:{bid}" visible="true"{img_attr}/>')

    out = HEADER.format(tab=HIDDEN_TAB, ribbon=RIBBON) + "\n".join(lines) + "\n" + FOOTER
    with open(ICONS_ONLY, "w", encoding="utf-8") as fh:
        fh.write(out)
    return order


def main():
    check_only = "--check-only" in sys.argv
    ribbon_xml = read(RIBBON)
    buttons = hidden_tab_buttons(ribbon_xml)
    if not buttons:
        sys.exit(f"ERROR: no VistaType buttons found on the {HIDDEN_TAB} tab")

    print(f"VistaType buttons on the hidden tab: {len(buttons)}")
    problems = validate_full(buttons)

    if problems:
        print("\nERROR: the toolbar and the ribbon tab disagree:")
        for p in problems:
            print(f"  - {p}")
        print("\nFix src/ribbon/customUI14.xml or installer/qat-template.officeUI so they match.")
        sys.exit(1)
    print(f"  {FULL}: every VistaType entry checks out")

    if not check_only:
        order = generate_icons_only(buttons, ribbon_xml)
        print(f"  wrote {ICONS_ONLY} ({len(order)} icons + 1 separator)")


if __name__ == "__main__":
    main()
