#!/usr/bin/env python3
"""Generate VistaType's ribbon tabs in Word.officeUI form (Linux-only).

WHY THIS EXISTS
---------------
Tabs defined in the add-in's embedded customUI do not appear in Word's
"File > Options > Customize the Ribbon" list, so a user cannot hide them, reorder them or
rename them. Jerry, 7/28/2026: "Even I want to hide the braille macro tab when I'm producing
large print, and it is not unusual that I will rearrange the tabs. Not being able to do these
things is not acceptable."

Tabs defined in the USER'S OWN Word.officeUI are ordinary custom tabs, so Word lists them and
all three become possible. This emits that form; Merge-Qat.ps1 installs it non-destructively.

THE FORM, AND WHY (verified on the build box, 7/28/2026)
--------------------------------------------------------
Each button is emitted as a REFERENCE to the button that already lives inside the add-in:

    <mso:control idQ="x1:btn_Lp_File_Fix_Sequence" visible="true"/>

not as the legacy standalone macro button (`<mso:button onAction="Lp_File_Fix_Sequence"/>`).
Both render and both fire -- tested -- but the reference form is right for three reasons:

  1. It keeps the dispatcher. `RibbonAction` clears Sh_Pos_Depth / Sh_Pos_Saved on every
     press, added 7/26/2026 so a macro that stops on an error cannot wedge the
     return-to-where-you-were feature for the rest of the session. A standalone onAction
     button calls the sub directly and skips that guard -- for 43 of the 49 buttons.
  2. Word takes the label and the icon from the add-in's own definition, so none of that text
     is duplicated here and none of it can drift. This file is pure layout.
  3. Only one meaning of the `x1` prefix is ever emitted (the installed .dotm path), the same
     meaning the Quick Access Toolbar templates use.

The hidden `tab_LP_and_BRL_QAT_Icons` is deliberately skipped: it must stay embedded in the
.dotm, because every toolbar already installed in the field references its six btn_* ids.

Usage:  python3 tools/lib/build_ribbon_tabs.py [--check-only]
"""
import re
import sys
import xml.etree.ElementTree as ET

RIBBON = "src/ribbon/customUI14.xml"
OUT = "installer/ribbon-tabs.officeUI"
SKIP_TAB = "tab_LP_and_BRL_QAT_Icons"
# Buttons that have shipped and been taken off every visible tab (customUI14.xml explains). Kept
# embedded so a toolbar already naming one does not go blank; never offered as a tab of its own.
RETIRED_TAB = "tab_VT_Retired_Buttons"

# An XML comment may not contain a double hyphen. Word and PowerShell both refuse the whole
# file if it does, and the only symptom is an install that silently leaves the ribbon alone.
HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/lib/build_ribbon_tabs.py from {ribbon}.
     Do not edit by hand; edit the ribbon source instead.

     VistaType's tabs in the form Word writes for a user's own custom tabs, so that Word lists
     them in Customize the Ribbon and they can be hidden, reordered and renamed. Each button is
     a reference to the button inside the add-in, so clicks still go through the RibbonAction
     dispatcher and the labels and icons are not duplicated here.

     The x1 namespace below is a placeholder. Merge-Qat.ps1 swaps in the real path of the
     installed add-in, and reassigns the prefix if the user already has x1 bound to something
     else (Jerry's own machine and the build box both have it bound to SWIFT, which is installed on
     both and puts its own tab, "Braille", beside VistaType LP's "Braille Macros"). -->
<mso:customUI xmlns:x1="__VT_DOTM_PATH__" xmlns:mso="http://schemas.microsoft.com/office/2009/07/customui">
  <mso:ribbon>
    <mso:tabs>
"""

FOOTER = """    </mso:tabs>
  </mso:ribbon>
</mso:customUI>
"""


def read(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def attr(el, name):
    """Read an attribute as LITERAL SOURCE TEXT.

    Deliberately not parsed: keeping the raw text means entities such as &amp;&amp; and
    &#8594; pass through byte-identical. Decoding and re-escaping them by hand is exactly
    where an ampersand gets doubled or an arrow turns to mojibake.
    """
    m = re.search(rf'\b{name}="([^"]*)"', el)
    return m.group(1) if m else None


def visible_tabs(ribbon_xml):
    """The tabs a user should be able to control, in source order."""
    out = []
    for m in re.finditer(r'<tab\b[^>]*>.*?</tab>', ribbon_xml, re.S):
        block = m.group(0)
        head = block[: block.index(">") + 1]
        tab_id = attr(head, "id")
        if tab_id in (SKIP_TAB, RETIRED_TAB):
            continue
        out.append((tab_id, attr(head, "label"), block))
    return out


def groups_of(tab_block):
    for m in re.finditer(r'<group\b[^>]*>.*?</group>', tab_block, re.S):
        block = m.group(0)
        head = block[: block.index(">") + 1]
        yield head, block


def sanitize(label):
    return re.sub(r"[^A-Za-z0-9_]", "_", label)


def generate(ribbon_xml):
    lines = []
    counts = []
    for tab_id, label, block in visible_tabs(ribbon_xml):
        vt_tab = "vt_tab_" + sanitize(label)
        # insertBeforeQ (the qualified form), never insertBeforeMso, and never an anchor in a
        # foreign namespace -- the legacy file anchored one tab after Adobe Acrobat's tab,
        # which only resolved on a machine that had Acrobat.
        lines.append(f'      <mso:tab id="{vt_tab}" label="{label}" '
                     f'insertBeforeQ="mso:TabInsert" visible="true">')
        n_buttons = 0
        for ghead, gblock in groups_of(block):
            gid = "vt_" + attr(ghead, "id")
            glabel = attr(ghead, "label")
            gimage = attr(ghead, "imageMso")
            img = f' imageMso="{gimage}"' if gimage else ""
            lines.append(f'        <mso:group id="{gid}" label="{glabel}"{img} autoScale="true">')
            for b in re.finditer(r"<button\b[^>]*/>", gblock):
                bid = attr(b.group(0), "id")
                lines.append(f'          <mso:control idQ="x1:{bid}" visible="true"/>')
                n_buttons += 1
            for c in re.finditer(r"<control\b[^>]*/>", gblock):
                cid = attr(c.group(0), "idMso")
                if cid:
                    lines.append(f'          <mso:control idQ="mso:{cid}" visible="true"/>')
            lines.append("        </mso:group>")
        lines.append("      </mso:tab>")
        counts.append((label, vt_tab, n_buttons))
    return "\n".join(lines) + "\n", counts


def check_anchors(text):
    """Every anchor must be in the mso namespace, or it will not resolve on another machine."""
    bad = [a for a in re.findall(r'insert(?:Before|After)Q="([^"]*)"', text)
           if not a.startswith("mso:")]
    if bad:
        sys.exit(f"ERROR: anchors outside the mso namespace would not resolve elsewhere: {bad}")


def validate_xml(path):
    try:
        ET.parse(path)
    except ET.ParseError as exc:
        sys.exit(f"ERROR: {path} is not well-formed XML: {exc}")


def check_ids_are_stable(ribbon_xml):
    """A button id is a published contract. Fail loudly if one that has shipped disappears.

    Both the Quick Access Toolbar and (from 3.0.34) the ribbon tabs live in the USER'S
    Word.officeUI and reference our buttons by id. Rename or delete a button here and every
    copy already installed in the field points at nothing: the entry renders blank, with no
    error and nothing to explain it. The user's own file is not ours to migrate.

    So SHIPPED_IDS is append-only. A new button just adds a line. Removing one is a deliberate
    decision to break existing installs, and should be made on purpose, not by a rename.
    """
    shipped_path = "installer/ribbon-button-ids.txt"
    current = set(re.findall(r'<button id="([^"]+)"', ribbon_xml))

    try:
        with open(shipped_path, "r", encoding="utf-8") as fh:
            shipped = {ln.strip() for ln in fh
                       if ln.strip() and not ln.startswith("#")}
    except FileNotFoundError:
        with open(shipped_path, "w", encoding="utf-8") as fh:
            fh.write("# Button ids that have shipped. Append-only: the user's installed\n"
                     "# ribbon tabs and Quick Access Toolbar reference these by id, and a\n"
                     "# removed id renders as a blank entry on their machine with no error.\n"
                     "# Generated by tools/lib/build_ribbon_tabs.py; commit changes to it.\n")
            for b in sorted(current):
                fh.write(b + "\n")
        print(f"  seeded {shipped_path} with {len(current)} button ids")
        return

    gone = sorted(shipped - current)
    if gone:
        sys.exit(
            f"ERROR: {len(gone)} button id(s) that have already shipped are no longer in "
            f"{RIBBON}:\n" +
            "".join(f"  - {g}\n" for g in gone) +
            "\nEvery ribbon tab and toolbar already installed references these by id; they\n"
            "would render blank with no error. Restore the id, or - if the removal is\n"
            f"deliberate - take the line out of {shipped_path} in the same change."
        )

    added = sorted(current - shipped)
    if added:
        with open(shipped_path, "a", encoding="utf-8") as fh:
            for b in added:
                fh.write(b + "\n")
        print(f"  {len(added)} new button id(s) recorded in {shipped_path}")


def main():
    check_only = "--check-only" in sys.argv
    ribbon_xml = read(RIBBON)

    body, counts = generate(ribbon_xml)
    if not counts:
        sys.exit(f"ERROR: no user-controllable tabs found in {RIBBON}")

    text = HEADER.format(ribbon=RIBBON) + body + FOOTER
    check_anchors(text)

    # NOT checked here: that every reference points at a button that exists. Both sides of
    # that comparison come from this same file, so it can never fail -- renaming a button
    # renames it in the reference too. The check that actually matters is below.
    check_ids_are_stable(ribbon_xml)

    print(f"user-controllable tabs: {len(counts)}")
    for label, vt_tab, n in counts:
        print(f"  {label:20} -> {vt_tab:28} {n} buttons")
    print(f"  (skipped {SKIP_TAB}: stays embedded, the toolbar depends on it)")
    print(f"  (skipped {RETIRED_TAB}: retired button ids, kept embedded for toolbars that name them)")

    if check_only:
        return
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    validate_xml(OUT)
    print(f"  wrote {OUT}, well-formed")


if __name__ == "__main__":
    main()
